# lightning.pytorch==2.x
seed_everything: 42
trainer:
  accelerator: auto
  devices: auto
  precision: 16-mixed
  max_epochs: 100
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: jute-disease-detection
      entity: grade-descent
      log_model: true
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss
        filename: "densenet-{epoch:02d}-{val_loss:.4f}"
        save_top_k: 1
        mode: min
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val_loss
        patience: 5
        mode: min

model:
  class_path: jute_disease.models.jute_classifier.JuteClassifier
  init_args:
    lr: 0.001
    freeze_backbone: true
    feature_extractor:
      class_path: jute_disease.models.dl_backbones.densenet.DenseNet
      init_args:
        pretrained: true

data:
  class_path: jute_disease.data.jute_datamodule.JuteDataModule
  init_args:
    data_dir: data/ml_split
    batch_size: 256
    use_weighted_sampler: false
